export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";


export const UPDATE_ASSIGNMENT_START = "UPDATE_ASSIGNMENT_START";
export const UPDATE_ASSIGNMENT_FAIL = "UPDATE_ASSIGNMENT_FAIL";
export const UPDATE_ASSIGNMENT_SUCCESS = "UPDATE_ASSIGNMENT_SUCCESS";


export const DELETE_ASSIGNMENT_START = "DELETE_ASSIGNMENT_START";
export const DELETE_ASSIGNMENT_FAIL = "DELETE_ASSIGNMENT_FAIL";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";


export const GET_GRADED_ASSIGNMENT_LIST_START =
  "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL =
  "GET_GRADED_ASSIGNMENTS_LIST_FAIL";
export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS =
  "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";

export const CREATE_GRADED_ASSIGNMENT_START = "CREATE_GRADED_ASSIGNMENT_START";
export const CREATE_GRADED_ASSIGNMENT_FAIL = "CREATE_GRADED_ASSIGNMENT_FAIL";
export const CREATE_GRADED_ASSIGNMENT_SUCCESS = "CREATE_GRADED_ASSIGNMENT_SUCCESS";

export const START_GRADED_ASSIGNMENT_START = "START_GRADED_ASSIGNMENT_START";
export const START_GRADED_ASSIGNMENT_FAIL = "START_GRADED_ASSIGNMENT_FAIL";
export const START_GRADED_ASSIGNMENT_SUCCESS = "START_GRADED_ASSIGNMENT_SUCCESS";


export const GET_ASSIGNMENTS_INSIGHTS_START = "GET_ASSIGNMENTS_INSIGHTS_START";
export const GET_ASSIGNMENTS_INSIGHTS_FAIL = "GET_ASSIGNMENTS_INSIGHTS_FAIL";
export const GET_ASSIGNMENTS_INSIGHTS_SUCCESS = "GET_ASSIGNMENTS_INSIGHTS_SUCCESS";


export const GET_INSIGHT_DETAIL_START = "GET_INSIGHT_DETAIL_START";
export const GET_INSIGHT_DETAIL_FAIL = "GET_INSIGHT_DETAIL_FAIL";
export const GET_INSIGHT_DETAIL_SUCCESS = "GET_INSIGHT_DETAIL_SUCCESS";


export const SEND_EMAIL_START = "SEND_EMAIL_START";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";